import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Poppins, Open_Sans } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"], variable: "--font-poppins", display: "swap" });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["300", "400", "500", "700"], variable: "--font-poppins", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${openSans.variable}`}>{children}</body>
    </html>
  );
}
